### ISSUE TITLE
unsatisfiedlink error GLIBC_2.11

### ISSUE THREAD

**Issue by heymjo** [dblock/oshi#105]
Hi,

Is there some server side dependency this library assumes to be present ? Deploying locally on windows my code works fine, however in our test environment i geth this :

```
java.lang.UnsatisfiedLinkError: /test/weblogic/_tmp/jna/jna4719478330789077213.tmp: /lib64/libc.so.6: version `GLIBC_2.11' not found (required by /test/weblogic/_tmp/jna/jna4719478330789077213.tmp)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
	at java.lang.Runtime.load0(Runtime.java:795)
	at java.lang.System.load(System.java:1062)
	at com.sun.jna.Native.loadNativeLibraryFromJar(Native.java:771)
	at com.sun.jna.Native.loadNativeLibrary(Native.java:697)
	at com.sun.jna.Native.(Native.java:127)
	at com.sun.jna.Structure.(Structure.java:146)
	at oshi.hardware.platform.linux.LinuxGlobalMemory.getTotal(LinuxGlobalMemory.java:81)
```

Jorg

**Comment by dbwiddis** [comment]
Well, that would be the Linux C library, glibc.so ...

**Comment by dbwiddis** [comment]
Have you been able to install the linux C library on your weblogic server to resolve this?

**Comment by heymjo** [comment]
No, and it is not going to happen due to datacenter policies :-(

Op do 31 dec. 2015 06:29 schreef dbwiddis <notifications@github.com>:

**Comment by dbwiddis** [comment]
Hmm.

I included libc because I thought it was ubiquitous on Linux distributions.   We already parse /proc/meminfo for the available memory and we could easily just grab the total from there (possibly even at the same time), omitting the need for this dependency.   While we generally prefer native calls to parsing files, I think removing a dependency to a C library that isn't guaranteed trumps that preference.

**Comment by dbwiddis** [comment]
I've used try/catch on the sysinfo calls for total memory and uptime, to remove this dependence.  If the C library is present, it will use that. Otherwise it will fall back to /proc/meminfo (for total) and return 0 for uptime.
