### ISSUE TITLE
java.lang.NullPointerException: null | when extract display (not connected to raspberry-pi)

### ISSUE THREAD

**Issue by pcollaog** [dblock/oshi#130]
NullPointer when extract not connected display on raspberry-pi.
<pre>
java.lang.NullPointerException: null
        at oshi.hardware.platform.linux.LinuxDisplay.getDisplays(LinuxDisplay.java:74)
        at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.getDisplays(LinuxHardwareAbstractionLayer.java:133)
        at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.toJSON(LinuxHardwareAbstractionLayer.java:155)
        at oshi.SystemInfo.toJSON(SystemInfo.java:120)
</pre>

**Comment by dbwiddis** [comment]
Looks like `xrandr` doesn't work....
