### ISSUE TITLE
NPE if it runs in system account (as service)

### ISSUE THREAD

**Issue by lundefugl** [dblock/oshi#182]
We use OSHI to monitor some system properties on runtime. It works fine, but if our program is running as service we get a NPE (on call `systemInfo.getHardware().getFileStores()`).
Maybe its a problem with mounted network drives in the user login session. From a system account the drive-letters are visible, but not accessible. I expect the identical behavior to CD drives without a CD.

```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at javax.swing.SwingWorker.get(SwingWorker.java:602)
	at oshi.software.os.windows.WindowsFileSystem.getFileStores(WindowsFileSystem.java:98)
	at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.getFileStores(WindowsHardwareAbstractionLayer.java:78)
...
Caused by: java.lang.NullPointerException
	at sun.awt.shell.Win32ShellFolder2.access$200(Win32ShellFolder2.java:72)
	at sun.awt.shell.Win32ShellFolder2$1.call(Win32ShellFolder2.java:242)
	at sun.awt.shell.Win32ShellFolder2$1.call(Win32ShellFolder2.java:237)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at sun.awt.shell.Win32ShellFolderManager2$ComInvoker$3.run(Win32ShellFolderManager2.java:547)
	... 1 more

```

**Comment by dbwiddis** [comment]
Can you check out the latest 2.5-SNAPSHOT?  We completely rewrote the windows file stores to get rid of the swing worker thread that appears to be causing your issue.

**Comment by lundefugl** [comment]
Fantastic - it works with oshi-core-2.5-20160603.062404-24. 
Thank you very much.

**Comment by dbwiddis** [comment]
Excellent.  2.5 should be released this weekend.
