### ISSUE TITLE
Exceptions on windows disk and partition edge cases

### ISSUE THREAD

**Issue by lundefugl** [dblock/oshi#238]
Hello,

the new version fails on reading disk infos. The problem occurs when reading the data of a connected 
usb memory stick. 

Regards
Thomas

Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 2
	at java.lang.String.substring(String.java:1963)
	at oshi.util.ParseUtil.hexStringToString(ParseUtil.java:296)
	at oshi.hardware.platform.windows.WindowsDisks.getDisks(WindowsDisks.java:84)
	at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.getDiskStores(WindowsHardwareAbstractionLayer.java:70)
	at SystemInfoTest.main(SystemInfoTest.java:94)

![serial-number-parsing](https://cloud.githubusercontent.com/assets/1292880/17364367/1de0e03c-5980-11e6-803a-5157fd608688.png)

**Comment by lundefugl** [comment]
I have removed the usb stick. Now I have a other problem. The card reader has not partitions and I get a NullPointerException.

java.lang.NullPointerException
	at oshi.hardware.platform.windows.WindowsDisks.getDisks(WindowsDisks.java:96)
	at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.getDiskStores(WindowsHardwareAbstractionLayer.java:70)

**Comment by dbwiddis** [comment]
OK, I've fixed these on the SNAPSHOT. Can you confirm?

For the first error, my string parsing didn't account for the edge case of single characters or odd-length strings containing only parsable hex.  It would be useful for me to know what your WMI returns for the USB Stick serial number (I'm thinking it's a single character, possibly "0"?)  to help confirm the fix.

**Comment by lundefugl** [comment]
Many thanks.
Tomorrow I'm not in the office. I will test it friday morning. Then I can check also the WMI value.
It's now evening in europe and I'm at home.

**Comment by dbwiddis** [comment]
Thanks!  Actually, I just looked at the image you attached and the information is there.  It appears to be a single character, "\u001F" / ASCII 31.  So just testing it will be fine.

**Comment by lundefugl** [comment]
It works.
Thank you.
