### ISSUE TITLE
Exception while removing reference

### ISSUE THREAD

**Issue by dbwiddis** [dblock/oshi#74]
Randomly, but often, running the SystemInfoTest file on Windows results in this exception when the program terminates.
```
Exception while removing reference: java.lang.InterruptedException
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at sun.java2d.Disposer.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
Discussion of the issue in this SO thread:  http://stackoverflow.com/questions/2873449/occasional-interruptedexception-when-quitting-a-swing-application

Problematic code appears to be the FileSystemView object in WindowsFileSystem.

**Comment by dbwiddis** [comment]
http://stackoverflow.com/questions/32367929/interruptedexception-using-filesystemview-without-other-swing-components
